name: "Deploy Extractor API Resources to API Management"
on:
  push:
    branches:
      - "extractor-dryrun"
  workflow_dispatch:
    
jobs:
  extract_api:
    name: "Extract Todo API"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Install DevOps Toolkit
      uses: fortunkam/apim-devops-resource-kit-actions/install-resource-kit@v1.1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        releaseVersion: 0.7
    - name: Ensure the directory Exists
      working-directory: ./api/Extractor
      run: mkdir -p templates
    - name: Run the extractor Tool
      uses: fortunkam/apim-devops-resource-kit-actions/run-extractor@v1.1
      with:
        workingDirectory: ./api/Extractor
        configFile: extractorConfig.json
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.2
      with:
        name: templates
        path: ./api/Extractor/templates/**
        if-no-files-found: error
  deploy_api:
    name: "Deploy Todo API to Target"
    runs-on: ubuntu-latest
    needs: [ extract_api ]
    steps:
    - name: Download a Build Artifact
      uses: actions/download-artifact@v2.0.8
      with:
        name: templates
        path: templates
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Azure CLI script file
      uses: azure/CLI@v1
      with:
        azcliversion: 2.30.0
        inlineScript: |
          RESOURCE_GROUP='LunchBytes'
          APIM_NAME='lunchbytes-apim-target'
          az deployment group create -g $RESOURCE_GROUP --template-file ./templates/todo-globalServicePolicy.template.json --parameters ApimServiceName=$APIM_NAME
          az deployment group create -g $RESOURCE_GROUP --template-file ./templates/todo-tags.template.json --parameters ApimServiceName=$APIM_NAME
          az deployment group create -g $RESOURCE_GROUP --template-file ./templates/todo-backends.template.json --parameters ApimServiceName=$APIM_NAME
          az deployment group create -g $RESOURCE_GROUP --template-file ./templates/todo-todo-api.template.json --parameters ApimServiceName=$APIM_NAME
          az deployment group create -g $RESOURCE_GROUP --template-file ./templates/todo-apiTags.template.json--parameters ApimServiceName=$APIM_NAME
    - name: Azure Logout
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
          az logout
          az cache purge
          az account clear